server:
  port: 8080
  servlet:
    context-path: /devweek

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://jtknnvnpscssov:fb78345d6799728e6e06ccde6e7f90b7d3953b421ff60596d955657fed20968d@ec2-52-0-114-209.compute-1.amazonaws.com:5432/d7d1nmc3cpbu1a
    username: jtknnvnpscssov
    password: fb78345d6799728e6e06ccde6e7f90b7d3953b421ff60596d955657fed20968d
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para a DevWeek DIO - Santander
  version: 1.0